name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar pruebas de Healthcheck (Mock)
        run: python healthcheck.py

      - name: Ejecutar pruebas de Reporte de Sprint
        run: python sprint_report.py